swagger: "2.0"
info:
  description: "GroupDesc"
  version: "v1"
  title: "aops_agent"
basePath: "/v1"
tags:
- name: "aops_agent"
- name: "plugin"
schemes:
- "https"
paths:
  /agent/basic/info:
    get:
      tags:
      - "aops_agent"
      description: "获取主机基础信息"
      operationId: "get_host_info"
      parameters:
        - name: access_token
          in: header
          description: 授权码
          type: string
          required: true
      responses:
        "200":
          description: "主机的基本信息"
          schema:
            $ref: "#/definitions/get_host_info_rsp"
      x-swagger-router-controller: "aops_agent.controllers.agent_controller"
  /agent/plugin/start:
    get:
      tags:
        - "agent"
      description: "启动插件。暂时不支持指定配置文件启动"
      operationId: "start_plugin"
      parameters:
        - name: "plugin_name"
          in: "query"
          description: "插件名"
          required: true
          type: "string"
      responses:
        "200":
          description: "主进程PID"
          schema:
            type: "string"
      x-swagger-router-controller: "aops_agent.controllers.plugin_controller"
  /agent/plugin/stop:
    get:
      tags:
        - "agent"
      description: "停止插件"
      operationId: "stop_plugin"
      parameters:
        - name: "plugin_name"
          in: "query"
          description: "插件名"
          required: true
          type: "string"
      responses:
        "200":
          description: ""
          schema:
            type: "string"
      x-swagger-router-controller: "aops_agent.controllers.plugin_controller"
  /agent/collect/items/change:
    post:
      tags:
        - "agent"
      description: "改变agent中各插件的采集项 。\n插件名称放在外面一层"
      operationId: "change_collect_items"
      parameters:
        - in: "body"
          name: "collect_items_status"
          description: "修改的采集项信息"
          required: true
          schema:
            $ref: "#/definitions/agent_collect_items_change"
      responses:
        "200":
          description: "返回设置文件/配置失败的列表"
          schema:
            type: "object"
            example:
              plugin1:
                - "failure1"
                - "failure2"
              plugin2:
                - "failure1"
                - "failure2"
            additionalProperties:
              type: "array"
              items:
                type: "string"
      x-swagger-router-controller: "aops_agent.controllers.plugin_controller"
  /agent/plugin/info:
    get:
      tags:
        - agent
      description: 获取agent插件运行信息
      operationId: agent_plugin_info
      parameters:
        - name: access_token
          in: header
          required: true
          description: 授权码
          type: string
      responses:
        '200':
          description: 获取插件运行信息响应
          schema:
            type: array
            items:
              $ref: '#/definitions/GetAgentPluginInfoRsp'
        '400':
          description: 错误响应
          schema:
            $ref: '#/definitions/ErrorRsp'
      x-swagger-router-controller: "aops_agent.controllers.agent_controller"
definitions:
  ErrorRsp:
    required:
    - "error_code"
    - "error_msg"
    properties:
      error_code:
        type: "string"
        description: "错误码"
        minLength: 8
        maxLength: 36
      error_msg:
        type: "string"
        description: "错误描述"
        minLength: 2
        maxLength: 512
    description: "失败时返回的错误对象"
  get_host_info_rsp:
    description: "获取主机基本信息"
    properties:
      os:
        type: "object"
        description: "操作系统信息"
        properties:
          os_version:
            type: "string"
            description: "操作系统版本"
          kernel:
            type: "string"
            description: "kernel版本"
          bios_version:
            type: "string"
            description: "bios版本"
        required:
        - "kernel"
        - "os_version"
        - "bios_version"
  collect_items:
    type: "object"
    description: "各插件采集的数据项信息。对gopher来讲是探针信息，对fluentd来讲是文件名/路径"
    example:
      gopher:
        probe1:
          - "info1"
          - "info2"
    additionalProperties:
      type: "object"
      additionalProperties:
        type: "string"
  agent_collect_items_change:
    description: 更改agen及已安装插件的采集项状态。
    type: object
    additionalProperties:
      additionalProperties:
        type: string
    example:
      fluentd:
        collectconfig1: start
        collectconfig2: start
        collectconfig3: start
      gopher:
        probe1: start
        probe2: start
        probe3: start
  GetAgentPluginInfoRsp:
    description: 获取agent插件信息响应
    properties:
      plugin_name:
        type: string
      is_installed:
        type: boolean
        description: 是否安装
      status:
        type: string
        description: 运行状态
      collect_items:
        description: 采集项信息
        type: array
        items:
          properties:
            probe_name:
              type: string
            probe_status:
              type: string
      resource:
        description: 资源占用值
        type: array
        items:
          properties:
            name:
              type: string
            limit_value:
              type: string
            current_value:
              type: string
    required:
      - plugin_name
      - collect_items
      - resource
      - is_installed
      - status