topo_relations:
  -
    type: host
    level: HOST
    dependingitems:
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: host
  -
    type: container
    level: CONTAINER
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: container
  -
    type: appinstance
    level: APPLICATION
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: container
            matches:
              -
                from: pgid
                to: pid
              -
                from: machine_id
                to: machine_id
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: appinstance
  -
    type: system_proc
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: appinstance
            matches:
              -
                from: pgid
                to: pgid
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: system_proc
  -
    type: thread
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: bind
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: udp
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: connect
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: listen
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: tcp_link
    level: RPC
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
      -
        id: is_server
        layer: direct
        toTypes:
          -
            type: ipvs_link
            matches: &lb_link_server_match
              -
                from: server_ip
                to: server_ip
              -
                from: server_port
                to: server_port
            requires: &lb_link_server_require
              -
                side: from
                label: role
                value: 0
          -
            type: nginx_link
            matches: *lb_link_server_match
            requires: *lb_link_server_require
          -
            type: haproxy_link
            matches: *lb_link_server_match
            requires: *lb_link_server_require
      -
        id: is_client
        layer: direct
        toTypes:
          -
            type: ipvs_link
            matches: &lb_link_client_match
              -
                from: client_ip
                to: client_ip
              -
                from: server_ip
                to: virtual_ip
              -
                from: server_port
                to: virtual_port
            requires: &lb_link_client_require
              -
                side: from
                label: role
                value: 1
          -
            type: nginx_link
            matches: *lb_link_client_match
            requires: *lb_link_client_require
          -
            type: haproxy_link
            matches: *lb_link_client_match
            requires: *lb_link_client_require
      -
        id: is_peer
        layer: direct
        toTypes:
          -
            type: tcp_link
            matches:
              -
                from: server_ip
                to: server_ip
              -
                from: server_port
                to: server_port
              -
                from: client_ip
                to: client_ip
            conflicts:
              -
                from: role
                to: role
  -
    type: ipvs_link
    level: LB
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: thread
            matches: &lb_link_belong_task
              -
                from: pid
                to: pid
              -
                from: machine_id
                to: machine_id
  -
    type: nginx_link
    level: LB
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: thread
            matches: *lb_link_belong_task
  -
    type: haproxy_link
    level: LB
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: thread
            matches: *lb_link_belong_task
  -
    type: ksliprobe
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: system_proc
            matches:
              -
                from: tgid
                to: tgid
